---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-from-jenkins
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node-from-jenkins
  template:
    metadata:
      name: node-from-jenkins
      labels:
        app: node-from-jenkins
    spec:
      containers:
      - name: node-from-jenkins
        image: sjc.ocir.io/orasenatdpltintegration03/node-js-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ocir-creds
---
apiVersion: v1
kind: Service 
metadata:
  name: node-from-jenkins
  labels:
    app: node-from-jenkins
spec:
  selector:
    app: node-from-jenkins
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-from-jenkins-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /node-nginx
        pathType: Prefix
        backend:
          service:
            name: node-from-jenkins
            port:
              number: 80
